### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by noe-gif** [Gloumy/diaporama#5]
Hi ! I'm trying to contact you because I have one or two questions about the use of DRAW api wrapper but I can't manage to find you on social media so I'm trying here ^^. I'm doing a project in flutter where I need to use the reddit API but I'm facing some issues. Hope I can take 5 minutes of your time. I come from belgium too ! Greetings, great work by the way.

**Comment by Gloumy** [comment]
I've emailed you on the adresse on your github profile with some contact addresses
